name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"  # Every Saturday at 8:00 AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant write access
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Sync LeetCode solutions
        uses: joshcai/leetcode-sync@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: leetcode-solutions
          filter-duplicate-secs: 86400  # 1 day in seconds
